function [paramVec,fval,reconstructedTSmatrix,startTimesSorted_A, ...
        stimValuesSorted_A, startTimesSorted_B, stimValuesSorted_B, ...
        actualStimulusValues] ...
          = fitNeuralParams(startTimesSorted,stimValuesSorted,tsFileNames, ...
          TS_timeSamples,stimDuration,stepFunctionRes,cosRamp,stimTypeArr, ...
          t_convolve,BOLDHRF,cleanedData,paramVec)
      
% set options      
options = optimoptions('fmincon','Diagnostics','on','Display','iter','Algorithm','active-set','MaxIter',100);

% convert parameter struct to initial vector
prmVec0 = paramVec;

f = @(prmVec)forwardModelObjectiveFunction(startTimesSorted,stimValuesSorted, ...
          TS_timeSamples,stimDuration,stepFunctionRes,cosRamp, stimTypeArr, ...
          t_convolve,BOLDHRF,cleanedData,prmVec);

% vlb = [0 0 0.01 0.001 0.1 0];
% vub = [20 5 0.5 0.01 0.5 2];
vlb = [];
vub = [];

[paramVec, fval] = fmincon(f,prmVec0,[],[],[],[],vlb,vub,[],options);

[reconstructedTSmatrix,startTimesSorted_A, ...
stimValuesSorted_A, startTimesSorted_B, stimValuesSorted_B, ...
actualStimulusValues,~] ...
                          = ...
forwardModel(startTimesSorted,stimValuesSorted,tsFileNames, ...
TS_timeSamples,stimDuration,stepFunctionRes,cosRamp,stimTypeArr, ...
t_convolve,BOLDHRF,cleanedData,paramVec);
      
gribble = 1;